### Register user
POST http://localhost:8000/backend/api/v1/register
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "strongpassword123"
}

### Login user
POST http://localhost:8000/backend/api/v1/login
Content-Type: application/x-www-form-urlencoded

username=test@example.com&password=strongpassword123


### Get current user profile
GET http://localhost:8000/backend/api/v1/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzU0NDk2NDUyfQ.-8W2wMWUE3C9m5LkNLGLHFxtVZW332vJJN7UyYXtjx0


### Upload Profile Image
POST http://localhost:8000/backend/api/v1/upload-profile-image/
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzU0NDE4MzE0fQ.HM2KlZViqk7laCi7bGkxtKeEo7dFPHBjwU-X20yP4Og

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="your_image.jpg"
Content-Type: image/jpeg

< @/home/dorna/Downloads/DropMeFiles_NKM9m/your_image.jpg >
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### Delete Profile Image
DELETE http://localhost:8000/backend/api/v1/delete-profile-image/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzU0NDk2NDUyfQ.-8W2wMWUE3C9m5LkNLGLHFxtVZW332vJJN7UyYXtjx0