"""Added progress tracker

Revision ID: a51cd771f418
Revises: a56bbdcda561
Create Date: 2025-08-14 21:22:24.812325

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a51cd771f418"
down_revision: Union[str, Sequence[str], None] = "a56bbdcda561"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "uploaded_links", sa.Column("last_watched_time", sa.Float(), nullable=True)
    )
    op.add_column(
        "uploaded_links", sa.Column("is_completed", sa.Boolean(), nullable=True)
    )
    op.alter_column(
        "uploaded_links",
        "duration_seconds",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "uploaded_links",
        "duration_seconds",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.drop_column("uploaded_links", "is_completed")
    op.drop_column("uploaded_links", "last_watched_time")
    # ### end Alembic commands ###
