"""Add playlist schema

Revision ID: a56bbdcda561
Revises: 2e482b524019
Create Date: 2025-08-11 21:44:35.603443

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a56bbdcda561"
down_revision: Union[str, Sequence[str], None] = "2e482b524019"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "playlist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "visibility",
            sa.Enum("PUBLIC", "PRIVATE", name="playlistvisibility"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_playlist_id"), "playlist", ["id"], unique=False)
    op.add_column(
        "uploaded_links", sa.Column("playlist_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "uploaded_links", "playlist", ["playlist_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "uploaded_links", type_="foreignkey")
    op.drop_column("uploaded_links", "playlist_id")
    op.drop_index(op.f("ix_playlist_id"), table_name="playlist")
    op.drop_table("playlist")
    # ### end Alembic commands ###
